MarketBard/MarketBard/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexView
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path(
        '__debug__/', include('debug_toolbar.urls')
    ))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MarketBard/orders/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from orders.views import OrdersListView, CreateOrderView, OrderView

app_name = 'orders'

urlpatterns = [
    path('', OrdersListView.as_view(), name='index'),
    path('order-create/', CreateOrderView.as_view(), name='create'),
    path('order/<int:pk>/', OrderView.as_view(), name='order')
]

MarketBard/users/urls.py
from django.urls import path
from users.views import UserProfileView, UserRegistrationView, UserLoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

MarketBard/orders/models.py
from django.db import models
from users.models import User
from products.models import Basket


# Create your models here.

class OrderQuerySet(models.QuerySet):
    def order_number(self):
        return self.id


class Order(models.Model):

    objects = OrderQuerySet.as_manager()

    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3

    status_choice = (
        (CREATED, 'Создано'),
        (PAID, 'Оплачено'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлено')
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    status = models.SmallIntegerField(default=CREATED, choices=status_choice)
    creation_date = models.DateTimeField(auto_now_add=True)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)
    result = models.DecimalField(max_digits=8, decimal_places=2)


    def __str__(self):
        return f'Пользователь:  {self.first_name} Номер товара: {self.last_name}'

MarketBard/orders/forms.py
from django import forms
from orders.models import Order


class CreateOrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Имя'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Фамилия'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Эл. почта'
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Россия, Москва, ул. Мира, дом 6'
    }))


    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

MarketBard/orders/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from orders.models import Order
from products.models import Basket
from orders.forms import CreateOrderForm
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class OrdersListView(ListView):
    template_name = 'orders/orders.html'
    queryset = Order.objects.all()

    def get_queryset(self):
        queryset = super(OrdersListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OrdersListView, self).get_context_data()
        context['orders'] = Order.objects.all()
        return context

class CreateOrderView(CreateView):
    template_name = 'orders/order-create.html'
    model = Order
    form_class = CreateOrderForm
    success_url = reverse_lazy('orders:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CreateOrderView, self).get_context_data()
        context['baskets'] = Basket.objects.all()
        return context

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        baskets = Basket.objects.filter(user=self.request.user)
        form.instance.result = sum([basket.sum() for basket in baskets])
        form.instance.basket_history = [basket.de_json() for basket in baskets]
        baskets.delete()
        return super(CreateOrderView, self).form_valid(form)



class OrderView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OrderView, self).get_context_data()
        return context

MarketBard/orders/templates/orders/order-create.html
{% extends 'products/main.html' %}
{% load static humanize %}

{% block style %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.count }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">{{ basket.product.name }}</h6>
                                <small class="text-muted">{{ basket.quantity }} шт.</small>
                            </div>
                            <span class="text-muted">{{ basket.sum|intcomma }} руб.</span>
                        </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ baskets.total_sum|intcomma }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-12 mt-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Адрес доставки</label>
                            {{ form.address }}
                        </div>


                    </div>
                    <hr class="my-4">
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Оплатить заказ</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

MarketBard/orders/templates/orders/order.html
{% extends 'products/main.html' %}
{% load static humanize %}


{% block style %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ №{{object.id}}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for basket in object.basket_history %}
                            <tr>
                                <th scope="row">
                                    {{ basket.product_name }}
                                </th>
                                <td>{{ basket.quantity }}</td>
                                <td>{{ basket.price| intcomma }} руб.</td>
                                <td>{{ basket.sum| intcomma }} руб.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого {{ object.result | intcomma }} руб.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

MarketBard/orders/templates/orders/orders.html
{% extends 'products/main.html' %}
{% load static %}


{% block style %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.creation_date }}</td>
                                <td>{{ order.result }} руб.</td>
                                <td>
                                    <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

MarketBard/orders/templates/orders/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Спасибо за заказ!</title>
    <link href="../vendor/css/auth.css" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Ваш заказ успешно сформирован.
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>