MarketBard/MarketBard/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexView
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path(
        '__debug__/', include('debug_toolbar.urls')
    ))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MarketBard/products/urls.py
from django.urls import path
from products.views import basket_add, basket_del, ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('<int:page>/', ProductsListView.as_view(), name='page'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('category/<int:category_id>/<int:page>/', ProductsListView.as_view(), name='category_page'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket_del/<int:product_id>/', basket_del, name='basket_del'),
]

MarketBard/users/urls.py
from django.urls import path
from users.views import UserProfileView, UserRegistrationView, UserLoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

MarketBard/products/models.py
from django.db import models

from users.models import User

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=128)
    descriptions = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    photo = models.ImageField(upload_to='products_images')
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def count(self):
        return sum(basket.quantity for basket in self)



class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Пользователь { self.user.username }, Товар: { self.product.name }'


    def sum(self):
        return self.product.price * self.quantity


    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

MarketBard/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import Products, ProductCategory

from django.core.paginator import Paginator
from products.models import Basket
from django.contrib.auth.decorators import login_required

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView


class IndexView(TemplateView):
    template_name = 'products/index.html'


class ProductsListView(ListView):
    model = Products
    template_name = 'products/products.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['category'] = ProductCategory.objects.all()
        return context

@login_required
def basket_add(request, product_id):
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def basket_del(request, product_id):
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    basket = baskets.first()
    basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

MarketBard/products/templates/products/index.html
{% extends 'products/main.html' %}
{% load static %}


{% block style %}
    <link href="{% static '/css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

MarketBard/products/templates/products/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Store</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block style %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index'%}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'orders:index' %}">Заказы</a></li>
                        {% if user.is_superuser or user.is_stuff %}
                        <li><a class="dropdown-item" href="/admin">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form method="post" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit">Выйти</button>
                            </form>
                        </li>
                    </ul>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static '/jquery/jquery.min.js'%}"></script>
<script src="{% static '/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static '/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>

</body>

</html>

MarketBard/products/templates/products/products.html
{% extends 'products/main.html' %}
{% load static %}


{% block style %}
   <link href="{% static '/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for ctg in category %}
                    <a href="{% url 'products:category' ctg.id %}" class="list-group-item">{{ ctg.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static '/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static '/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static '/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.photo.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }}</h5>
                            <p class="card-text">{{ product.descriptions }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'products:basket_add' product.id%}">
                                <button type="button" class="btn btn-outline-success" >Отправить в корзину</button>
                            </a>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    {% for page in page_obj.paginator.page_range %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Слудующая</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}